# volumes:
#   pgdata:
#     name: esd_pgdata
#   rabbitmq_data:
#     name: esd_rabbitmq_data

networks:
  dell-net:
    driver: bridge
    name: dell-net

services:

  discord:
    build: ./discord-bot
    container_name: discord-bot
    networks:
      - dell-net
    # ports:
    #   - "5200:5200"
    env_file:
      - ./discord-bot/.env

  tasks:
    build: ./services/atomic/tasks
    container_name: tasks
    networks:
      - spm-net
    ports:
      - "5000:5000"
    env_file:
      - ./services/atomic/tasks/.env

  user:
    build: ./services/atomic/user
    container_name: user
    networks:
      - spm-net
    ports:
      - "5100:5100"
    env_file:
      - ./services/atomic/user/.env

  schedule:
    build: ./services/atomic/schedule
    container_name: schedule
    networks:
      - spm-net
    ports:
      - "5300:5300"
    env_file:
      - ./services/atomic/schedule/.env

#   rabbitmq:
#     image: rabbitmq:3-management
#     container_name: rabbitmq
#     hostname: foodapp-rabbit
#     restart: always
#     ports:
#       - "5672:5672" # RabbitMQ Client Connection
#       - "15672:15672" # RabbitMQ Management UI
#     volumes:
#       - rabbitmq_data:/var/lib/rabbitmq
#     networks:
#       - spm-net
#     healthcheck: # Good Code
#       test: ["CMD", "rabbitmqctl", "status"]
#       interval: 10s
#       retries: 5
#       start_period: 20s
#       timeout: 5s

#   rabbitmq-setup:
#     build: ./rabbitmq-setup
#     container_name: amqp-setup
#     depends_on:
#       rabbitmq:
#         condition: service_healthy
#     networks:
#       - spm-net